spring:
  application.name: thumb-backend

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thumb_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Yxc13731926265

  # Redis Config
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 5000ms

  # Pulsar
  pulsar:
    client:
      service-url: pulsar://116.196.64.68:6650

# Redisson Config
redisson:
  address: redis://localhost:6379
  password: 
  database: 0
  timeout: 3000
  connection-pool-size: 64
  connection-minimum-idle-size: 10
  idle-connection-timeout: 10000
  connect-timeout: 10000
  retry-attempts: 3
  retry-interval: 1500

server:
  port: 8113
  servlet:
    context-path: /api

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yxc.thumbbackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn









